# Generated by Django 3.1.7 on 2021-04-15 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('COLTBLE', 'Collectible & art'), ('ELECTRO', 'Electronics'), ('FASHION', 'Fashion'), ('HOME', 'Home & garden'), ('MUSIC', 'Musical Instruments & garden'), ('TOY', 'Toys & hobbies')], default='TOY', max_length=10)),
                ('price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('photo', models.ImageField(upload_to='images/')),
                ('active', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3)),
                ('is_watchlist', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('starting_bid', models.DecimalField(decimal_places=1, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_item', to='auctions.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('bidding_datetime', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder_item', to='auctions.listings')),
            ],
        ),
    ]
