# Generated by Django 3.1.7 on 2021-04-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_listing_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active',
            new_name='active_listing',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='is_watchlist',
            new_name='watchlist',
        ),
    ]
